### ISSUE TITLE
Le cercle du chrono ne s'affiche pas (pomodoro)

### ISSUE THREAD

**Issue by Ilade-s** [Tifiloow/productivite-app#8]
![image](https://user-images.githubusercontent.com/76600778/121067986-fead7080-c7cb-11eb-9646-5c3577f775ad.png)
![image](https://user-images.githubusercontent.com/76600778/121068013-05d47e80-c7cc-11eb-8285-04b3d2b24634.png)

**Comment by BugProg** [comment]
Bonjour,

Problème résolu.

Il s'agissait d'une version test.
