### ISSUE TITLE
Can create account with give email, password...

### ISSUE THREAD

**Issue by BugProg** [Tifiloow/productivite-app#9]
Hi !

I can create an account without enter any information.

**Comment by Ilade-s** [comment]
oh really? We copied the login part, so I don't know how it works...
I will look a little to the code

**Comment by BugProg** [comment]
Ho yes !

I don't remember that !!



>  I will look a little to the code

Ok, thank you !

**Comment by Ilade-s** [comment]
I added some checks before adding the user when you sign up, so now it shouldn't be possible to create an account with an empty field in the form.
Reopen the Issue if the fix doesn't work for you
